### ISSUE TITLE
Adding StyleCop rules

### ISSUE THREAD

**Issue by distantcam** [Particular/Particular.CodeRules#2]
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/DOCUMENTATION.md

What rules from the StyleCop Analyzers should we add?
- [x] [SA1100](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1100.md) Do not prefix calls with base unless local implementation exists.
- [x] [SA1119](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1119.md) Statement must not use unnecessary parenthesis.
- [x] [SA1200](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1200.md) Using directives must be placed correctly.
- [x] [SA1410](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1410.md) Remove delegate parenthesis when possible.
- [x] [SA1411](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1411.md) Attribute constructor must not use unnecessary parenthesis.
- [x] [SX1101](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SX1101.md) Do not prefix local members with this.

cc @Particular/engineers

**Comment by danielmarbach** [comment]
We have recently incorporated style cop rules into this repository and will continue to extend them
