### ISSUE TITLE
New NuGet release for AwaitOrCaptureTasksAnalyzer please

### ISSUE THREAD

**Issue by RemcoBlok** [Particular/Particular.CodeRules#6]
Hi,

I'm interested in the AwaitOrCaptureTasksAnalyzer. Would it be possible to update the NuGet package with this new analyzer please? 

many thanks

Remco

**Comment by timbussmann** [comment]
@DavidBoike what was your plan with that new analyzer, is that releasable?

**Comment by timbussmann** [comment]
hey @RemcoBlok, we've released Particular.CodeRules 0.2 on Nuget. Please let us know if you encounter any issues with it.

**Comment by RemcoBlok** [comment]
@timbussmann thank you very much for the fast response. The analyzer works very well.
